[versions]

# Common

## Project Configuration

kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"

## Libs

### KotlinX

kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.6.2"

### Input / Output

ktor = "3.1.1"
okio = "3.10.2"

### Storage

sqldelight = "2.0.2"
datastore = "1.1.7"

### DI

koin = "4.0.2"

# Crypto

cryptographyKotlin = "0.4.0"
hash = "0.7.0"

### Architecture

decompose = "3.3.0"

### UI

### Compose

composeMultiplatform = "1.8.1"

compose-shimmer = "1.3.3"

haze = "1.6.4"

#### Images

coil = "3.2.0"

# Android

## Project Configuration

agp = "8.10.1"

android-compileSdk = "36"
android-targetSdk = "36"
android-minSdk = "21"

jdk-desugar = "2.1.5"

## Libs

### Core

androidx-core-ktx = "1.16.0"
androidx-appcompat = "1.7.0"

### UI

#### Compose

androidx-composeBom = "2025.05.01"
androidx-activity-compose = "1.10.1"
androidx-lifecycle = "2.9.0"

compost = "0.0.5"

compose-reorderable = "0.9.6"

#### Images

imageCropper = "4.5.0"
compressor = "3.0.1"

#### QR

zxing = "3.5.3"

### Navigation

composeDestinations = "1.10.1"

### Auth

androidx-credentials = "1.5.0"
credentials-google = "1.1.1"

# Apple

## Project Configuration

swiftKLib = "0.6.4"

[libraries]

# Plugins

gradlePlugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-ksp = { group = "com.google.devtools.ksp", name = "symbol-processing-gradle-plugin", version.ref = "ksp" }
gradlePlugin-android = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradlePlugin-composeMultiplatform = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "composeMultiplatform" }
gradlePlugin-composeCompiler = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-swiftKLib = { group = "io.github.ttypic.swiftklib", name = "io.github.ttypic.swiftklib.gradle.plugin", version.ref = "swiftKLib" }

# Common

## Libs

### KotlinX

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlinx-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin" }

### Input / Output

network-ktor-utils = { group = "io.ktor", name = "ktor-utils", version.ref = "ktor" }
network-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
network-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
network-ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
network-ktor-client-auth = { group = "io.ktor", name = "ktor-client-auth", version.ref = "ktor" }
network-ktor-client-contentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
network-ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "ktor" }
network-ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
network-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

### Storage

database-sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqldelight" }
database-sqldelight-driver-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
database-sqldelight-driver-native = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }

androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
androidx-datastore-core-okio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore" }

### DI

di-koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
di-koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
di-koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

# Crypto

cryptographyKotlin-asn1 = { group = "dev.whyoleg.cryptography", "name" = "cryptography-serialization-asn1-modules", version.ref = "cryptographyKotlin" }

hash-sha1 = { group = "org.kotlincrypto.hash", name = "sha1", version.ref = "hash" }
hash-sha256 = { group = "org.kotlincrypto.hash", name = "sha2", version.ref = "hash" }

### Architecture

decompose-core = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-extensions-android = { group = "com.arkivanov.decompose", name = "extensions-android", version.ref = "decompose" }
decompose-extensions-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }

### UI

### Compose

compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "compose-shimmer" }

haze = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }

#### Images

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-ktor = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

### Tests

kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }

# Android

## Project Configuration

jdk-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "jdk-desugar" }

## Libs

### Core

androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }

### UI

#### Compose

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-composeBom" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }

androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }

androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-materialIcons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-compose-uiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

compost-core = { group = "com.github.mephistolie.compost", name = "core", version.ref = "compost" }
compost-ui = { group = "com.github.mephistolie.compost", name = "ui", version.ref = "compost" }

compose-reorderable = { group = "org.burnoutcrew.composereorderable", name = "reorderable", version.ref = "compose-reorderable" }

#### Images

imageCropper = { group = "com.vanniktech", name = "android-image-cropper", version.ref = "imageCropper" }
compressor = { group = "id.zelory", name = "compressor", version.ref = "compressor" }

#### QR

zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }

### Navigation

composeDestinations-core = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "composeDestinations" }
composeDestinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "composeDestinations" }

### Auth

androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidx-credentials" }
androidx-credentials-playServices = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidx-credentials" }

credentials-google = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "credentials-google" }

[bundles]

hash = ["hash-sha1", "hash-sha256"]

[plugins]

# Project Configuration

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

swiftKLib = { id = "io.github.ttypic.swiftklib", version.ref = "swiftKLib" }

# Project Plugins

module-multiplatform-base = { id = "plugins.module.multiplatform.base", version = "unspecified" }
module-multiplatform-sdk = { id = "plugins.module.multiplatform.sdk", version = "unspecified" }
module-multiplatform-database = { id = "plugins.module.multiplatform.database", version = "unspecified" }
module-multiplatform-network = { id = "plugins.module.multiplatform.network", version = "unspecified" }
module-multiplatform-data = { id = "plugins.module.multiplatform.data", version = "unspecified" }
module-multiplatform-compose = { id = "plugins.module.multiplatform.compose", version = "unspecified" }
module-multiplatform-feature = { id = "plugins.module.multiplatform.feature", version = "unspecified" }

module-android-lib = { id = "plugins.module.android.lib", version = "unspecified" }
module-android-compose = { id = "plugins.module.android.compose", version = "unspecified" }
module-android-navigation = { id = "plugins.module.android.navigation", version = "unspecified" }
module-android-feature = { id = "plugins.module.android.feature", version = "unspecified" }
module-android-app = { id = "plugins.module.android.app", version = "unspecified" }
